### PR TITLE
Added logout #62 removed navbar useEffect #67 stop form submit with login-signup switch #65 netlify redirect #77 

### LINKED ISSUE #62: make logout button work

### LINKED ISSUE #65: Errors in console when using token login
Getting error when myToken is present in local storage but its value is undefined. I think we could get rid of that error by adding a check to the useEffect that triggers the tokenLogin, maybe something like myToken.length > 0

### PR DESCRIPTION
**Pull request by damien-rembert**
In app.js, I added everything for the new logout route.

In login.js, I removed the tokenLogin and useEffect duplicate (already in app.js).
I added a condition so that clicks on the switch button would not be considered as a submission

I created the logout.js component.

In utils/index.js I added the logout function that the component calls.

In navbar.js, I removed old comments.

In menuItems.js, I changed the route to the logout component.

Might fix #65 ?
Fixes #62 and #67

### CODE REVIEW

**Comment by Nateldn** [comment]
Nice work!  Login/Sign-up/ are working. Logout seems to be working too, however, results in a 404 (at least in the preview). For some reason the MenuItems component isn't handling this correctly. Do we need to include <Navigate to='/landing' />  
somewhere?

**Comment by damien-rembert** [comment]
> Logout seems to be working too, however, results in a 404

Argh I think it's because I redirected to `/Landing` instead of `/landing` but I'll put `/gallery` anyway as it's probably what makes the most sense

**Comment by Nateldn** [comment]
Yep, I think gallery makes sense. I'm being redirected here now https://deploy-preview-74--pixlrt.netlify.app/logout

**Comment by damien-rembert** [comment]
Yaay! It works!

**Review by Nateldn — APPROVED** [review]

**Pull request merged**
